# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
dist: trusty
sudo: false
before_script:
  - env | sort
  - ldd ./lib/phantom/bin/phantomjs
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
